name: Wake Render

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping Render (GET with retries)
        env:
          WAKE_URL: ${{ secrets.WAKE_URL }}
        run: |
          set -e

          if [ -z "$WAKE_URL" ]; then
            echo "WAKE_URL is not set"; exit 1;
          fi

          URLS=("$WAKE_URL")
          if [[ "$WAKE_URL" != */health ]]; then
            URLS+=("$WAKE_URL/health")
          fi

          success=""
          for url in "${URLS[@]}"; do
            echo "Try URL: $url"
            for i in 1 2 3; do
              echo "GET $url (attempt $i)"
              if curl -fsS -m 10 "$url"; then
                success=1; break
              else
                sleep 5
              fi
            done
            [ -n "$success" ] && break
          done

          if [ -z "$success" ]; then
            echo "Wake failed (all attempts)"; exit 1;
          fi

          echo "Wake succeeded"
